// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFCmbii7PTiYqEFAm39Za2hxYNbMkAQso',
    appId: '1:521109258372:web:e1e2d0528336bf370842d1',
    messagingSenderId: '521109258372',
    projectId: 'portscout-5c9aa',
    authDomain: 'portscout-5c9aa.firebaseapp.com',
    storageBucket: 'portscout-5c9aa.appspot.com',
    measurementId: 'G-KV8TP6FNSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxF82xcLLPqaRWw4wu_Vp29R9GsxKxPxk',
    appId: '1:521109258372:android:6334a36cc58537b80842d1',
    messagingSenderId: '521109258372',
    projectId: 'portscout-5c9aa',
    storageBucket: 'portscout-5c9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bMDh8DvMvowiEMOqlTqUJnAUspbcOfM',
    appId: '1:521109258372:ios:e94988d2a6420e0f0842d1',
    messagingSenderId: '521109258372',
    projectId: 'portscout-5c9aa',
    storageBucket: 'portscout-5c9aa.appspot.com',
    iosClientId: '521109258372-basf1o9qfbh9gbjqvju3voebcgfk4d47.apps.googleusercontent.com',
    iosBundleId: 'com.example.portscout',
  );
}
